feat!: support latest data models and testnet
Geo-Web-Project/browser pull request #28
Opened 2022-08-19 09:07 UTC by tnrdd

- Uses Next.js
- Uses Optimism Kovan tesnet
- Uses latest subgraph
- Uses latest data models

fixes #23 and #24

2022-08-19 18:46 UTC, gravenp reviewed
Looks good on my end! Great work @tnrdd & @10dimensions!

@codynhat you can merge after you've had a chance to review.

2022-08-19 21:04 UTC, codynhat requested changes

2022-08-19 21:04 UTC, codynhat commented on next.config.js
> +    ignoreBuildErrors: true,
Can we change this to `false` and make sure there are no build errors? I'm doing the same right now with the Cadastre.

2022-08-20 15:47 UTC, gravenp reviewed
Things still look good on my end after the refactor and the build-related changes.

2022-08-22 18:30 UTC, codynhat approved these changes

2022-08-22 18:30 UTC, merged